version: "3.5"
volumes:
  pgdata:
  labsecrets:
  labstore:

services:
  postgres:
    image: postgres:14-alpine
    env_file: .env.docker
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - lab
  redis:
    image: redis:6-alpine
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - lab
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
  # fileserver:
  #   image: nuxion/fileserver
  #   volumes:
  #     - ./fileserver.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 4444:4444
  #   networks:
  #     - lab
  control:
    image: nuxion/labfunctions:0.9.0-alpha.12
    volumes:
      - labsecrets:/secrets
      - labstore:/labstore
      - ${PWD}/cluster.example.yaml:/app/cluster.example.yaml
      - ${PWD}/.ssh/:/app/ssh
    restart: unless-stopped
    env_file: .env.docker
    environment:
      LF_SERVER: "yes"
    command: >
      lab web --apps workflows,history,projects,runtimes,clusters -A --workers 1 -L -I
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - lab
  agent:
    image: nuxion/labfunctions:0.9.0-alpha.12
    env_file: .env.docker
    environment:
      LF_SERVER: true
    command: >
      lab agent run --qnames cpu,build,control -m local/ba/example
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - labsecrets:/secrets
      - labstore:/labstore
      - ${PWD}/.ssh/:/app/ssh
    user: 1089:991
    networks:
      - lab
networks:
  lab: 